version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: refbot-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - refbot-mysql-data:/var/lib/mysql

  bot:
    image: ${IMAGE:-ghcr.io/rh8831/refbot:latest}   # Default points to your GHCR image
    container_name: refbot-bot
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      CHANNEL_ID: ${CHANNEL_ID}
      ADMINS: ${ADMINS}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_MIN_CONN: "1"
      MYSQL_MAX_CONN: "10"

volumes:
  refbot-mysql-data:
